services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./scripts/run-app:/usr/local/bin/run-app
      - ./scripts/build-app:/usr/local/bin/build-app
      - /tmp/.X11-unix:/tmp/.X11-unix
    restart: on-failure
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: "host"
    stdin_open: true
    tty: true