#!/bin/bash

cd /app

BACKTRACE=0
CACHE=0
RESET_CARGOLOCK=0

for arg in "$@"; do
  case "$arg" in
    --trace) BACKTRACE=1 ;;
    --cache) CACHE=1 ;;
    --gen-lock-file) RESET_CARGOLOCK=1 ;;
  esac
done

if [ "$RESET_CARGOLOCK" = 1 ]; then
  echo "Removing Cargo.lock"

  sleep 1

  [ -f Cargo.lock ] && rm Cargo.lock

  echo "Resetting cargo"

  sleep 1
  
  cargo generate-lockfile
fi

clear

[ "$BACKTRACE" = 1 ] && echo "Adding backtrace" && sleep 1 && export RUST_BACKTRACE=full
[ "$CACHE" = 1 ] && echo "Adding cache" && sleep 1 && export RUSTC_WRAPPER="sccache"

echo "Running cargo"

sleep 1

cargo run