#!/bin/bash

cd /app

BACKTRACE=0
CACHE=0
RESET_CARGOLOCK=0

for arg in "$@"; do
  case "$arg" in
    --trace) BACKTRACE=1 ;;
    --cache) CACHE=1 ;;
    --gen-lock-file) RESET_CARGOLOCK=1 ;;
  esac
done

if [ "$RESET_CARGOLOCK" = 1 ]; then
    [ -f Cargo.lock ] && rm Cargo.lock

    cargo generate-lockfile
fi

clear

[ "$BACKTRACE" = 1 ] && export RUST_BACKTRACE=1
[ "$CACHE" = 1 ] && export RUSTC_WRAPPER="sccache"

cargo run